List<String> ages = [
  'RKO świeżorodka',
  'Poniżej 1 miesiąca',
  '1 miesiąc',
  '2 miesiące',
  '3 miesiące',
  '4 miesiące',
  '5 miesiący',
  '6 miesiący',
  '7 miesiący',
  '8 miesiący',
  '9 miesiący',
  '10 miesiący',
  '11 miesiący',
  '12 miesiący',
  '18 miesiący',
  '2 lata',
  '3 lata',
  '4 lata',
  '5 lat',
  '6 lat',
  '7 lat',
  '8 lat',
  '9 lat',
  '10 lat',
  '11 lat',
  '12 lat',
  'powyżej 12 lat',
];
