List<String> drugsList = [
  'Waga',
  'Dolna granica RR',
  'Prawidłowy oddech',
  'Prawidłowe tętno',
  'Poziom glukozy',
  'Maska twarzowa',
  'Rurka intubacyjna',
  'Laryngoskop',
  'Maska krtaniowa',
  'Defibrylacja',
  'Kardiowersja',
  'Adenozyna',
  'Adrenalina',
  'Adrenalina anafilaksja',
  'Adrenalina w pompie',
  'Amiodaron',
  'Atropina',
  'Deksametazon',
  'Fentanyl',
  'Furosemid',
  'Glukagon',
  'Glukoza 20%',
  'Hydrokortyzon',
  'Ibuprofen',
  'Ketonal',
  'Klemastin',
  'Klonazepam',
  'Magnez 20%',
  'Midazolam',
  'Morfina',
  'NaHCO3',
  'Nalokson',
  'Paracetamol - czopki',
  'Paracetamol - wlew',
  'Relanium',
  'Relsed wlewka',
  'Salbutamol',
  'Wlew 0,9% NaCl',
];
